### ISSUE TITLE
copy-paste fails

### ISSUE THREAD

**Issue by chris4git** [egzumer/uvk5-chirp-driver#1]
Hi,
copy-paste of lines don't work : on paste the memory number turns red but line stay empty : 

![image](https://github.com/egzumer/uvk5-chirp-driver/assets/23280864/216d7ceb-ac2a-40e7-a322-b9cc6c297afe)

Thanks for your work
Chris

**Comment by egzumer** [comment]
Hover a mouse over the red. See what is the error. Show what you are pasting.

**Comment by chris4git** [comment]
The last paste was the line 103 (downloaded from the radio).
Nothing displayed when hovering but this on the console : 

> ERROR: Failed to run set_memory(Memory 105: 446.193750/0.000000 NFM (PMR 16) r88.5  c88.5  d023 NN [6.25], )
> Traceback (most recent call last):
>   File "/home/clavelei/.local/lib/python3.10/site-packages/chirp/wxui/common.py", line 280, in do_radio
>     job.result = getattr(self._radio, fn)(*a, **k)
>   File "/home/clavelei/Téléchargements/uvk5_EGZUMER(1).py", line 2108, in set_memory
>     _mem.set_raw(bytes("\x00" * 10 +
>   File "/home/clavelei/.local/lib/python3.10/site-packages/chirp/bitwise.py", line 809, in set_raw
>     raise ValueError("Struct size mismatch during set_raw()")
> ValueError: Struct size mismatch during set_raw()
>
