### ISSUE TITLE
Use of uvk5_EGZUMER.py prevents option to turn Duplex "OFF"

### ISSUE THREAD

**Issue by Big-Mal99** [egzumer/uvk5-chirp-driver#12]
the option to turn Duplex off has disappeared and can't be copied into chirp

**Comment by egzumer** [comment]
I don't understand what you trying to say. Duplex off is available.

**Comment by Big-Mal99** [comment]
Thanks for your response.

When I download from the radio using CHIRP with module uvk5_EGZUMER.py
installed and radio option "UV-K5" the option for Duplex "OFF" exists.

When I download from the radio using the same CHIRP with module uvk5_EGZUMER.py
installed and radio option "UV-K5(egzumer)", to access the additional Basic
Settings, the option for Duplex "OFF" dooes not exist.

I hope this clarifies the problem

Malcolm

**Comment by ErikS-web** [comment]
Can you make a print screen of both ?
See my example

![Compare](https://github.com/egzumer/uvk5-chirp-driver/assets/148579604/8acf3964-d4ec-4499-bb63-eea69e12482e)

**Comment by egzumer** [comment]
Did you use the latest version of the driver from this repo? Did you try chirp_egzumer. exe from release?

**Comment by Big-Mal99** [comment]
Thanks for the response.  I have obviously been using an older version of
chirp_egzumer.  Everything seems OK now
Sorry for troubling you

Malcolm
