### ISSUE TITLE
Menu settings and custom key assignments are not preserved

### ISSUE THREAD

**Issue by InsanePup** [egzumer/uvk5-chirp-driver#15]
If I download from radio and upload to radio, any custom key assignments and non-default menu settings are reset to default.

**Comment by egzumer** [comment]
use the proper driver in the chirp

**Comment by ErikS-web** [comment]
Pse. 

First update, to the latest version, or load the driver manually.
And test again.

I load "manually" with file parameters. And that works fine.

This parameter-change just tested
![Knipsel](https://github.com/egzumer/uvk5-chirp-driver/assets/148579604/1ecebd94-c1e3-4cd0-be2a-2ec41edaacc2)

**Comment by egzumer** [comment]
> I'm using your custom build of Chirp. Does that not automatically load the k5 driver?

It does, use the correct one, you didn't check at all what drivers are available.
