### ISSUE TITLE
Change text of Advanged settings "Frequency mode allowed" into "VFO mode allowed"

### ISSUE THREAD

**Issue by ErikS-web** [egzumer/uvk5-chirp-driver#20]
Suggest to change line 1884

        freqModeAllowedSetting = RadioSetting("freq_mode_allowed", "Frequency mode allowed", val)

into 

        freqModeAllowedSetting = RadioSetting("freq_mode_allowed", "VFO mode allowed", val)

**Comment by egzumer** [comment]
VFO is Variable Frequency Oscillator. There is no VFO mode.

**Comment by ErikS-web** [comment]
There is an VFO button on the keyboard. 

That is blocked with this parameter ;-)

**Comment by egzumer** [comment]
> There is an VFO button on the keyboard.

Well, there is no way to change that in software.
