### ISSUE TITLE
Frequencies 300-350  "out of supported range"

### ISSUE THREAD

**Issue by Lucasvth** [egzumer/uvk5-chirp-driver#21]
Can't get frequencies between 300 and 350 programmed with chirp on UV-K5.

![Frequency out of range](https://github.com/egzumer/uvk5-chirp-driver/assets/156336296/861a0687-a963-4eb4-985f-3a5273854dd5)

**Comment by joc2** [comment]
it's fix now.

**Comment by Lucasvth** [comment]
Where is the fix? In the upcoming version of chip? because unfortunately I haven't had any luck yet with programming between this range.

**Comment by joc2** [comment]
on page egzumer. you need to reload the driver in chirp and read the radio to get access to it.
![image](https://github.com/egzumer/uvk5-chirp-driver/assets/56229329/00e76ba6-c927-4bba-891d-ccfe6ad41a7a)

**Comment by joc2** [comment]
![image](https://github.com/egzumer/uvk5-chirp-driver/assets/56229329/18b38915-8717-4312-8863-682e17583515)

**Comment by Lucasvth** [comment]
Thanks. Got it to work!
