### ISSUE TITLE
unable to download firmware on Linux

### ISSUE THREAD

**Issue by Carpintonto** [egzumer/uvk5-chirp-driver#28]
Ubuntu 22.04.3 LTS (Python 3.10.12) - CHIRP next-20240117 - Using port '/dev/ttyUSB0'

[chirp_debug-5btxklba.txt](https://github.com/egzumer/uvk5-chirp-driver/files/13970696/chirp_debug-5btxklba.txt)

**Comment by joc2** [comment]
strange, your radio should respond to the hello request with the firmware NAME   and it reply with the hello request instead .. weird... 
the radio is in normal state ???  mean power up normaly. 

here is my communication.. but under windows..

[2024-01-18 07:40:37,238] chirp.loaded.uvk5_egzumer - DEBUG: Sending hello packet
[2024-01-18 07:40:37,238] chirp.loaded.uvk5_egzumer - DEBUG: **Sending** command (unobfuscated) len=0x0008:
000: 14 05 04 00 6a 39 57 64   ....j9Wd

[2024-01-18 07:40:37,265] chirp.loaded.uvk5_egzumer - DEBUG: **Received** reply (unobfuscated) len=0x0028:
**000: 15 05 24 00 45 47 5a 55   ..$.EGZU
008: 4d 45 52 20 76 30 2e 32   MER.v0.2**
016: 31 00 00 00 00 00 00 20   1......
024: 00 00 00 00 00 00 00 00   ........
032: 00 00 00 00 00 00 00 00   ........

and your : 

[2024-01-17 16:46:37,481] chirp.loaded.uvk5_egzumer - DEBUG: Sending hello packet
[2024-01-17 16:46:37,481] chirp.loaded.uvk5_egzumer - DEBUG: **Sending** command (unobfuscated) len=0x0008:
000: 14 05 04 00 6a 39 57 64   ....j9Wd

[2024-01-17 16:46:37,488] chirp.loaded.uvk5_egzumer - DEBUG: **Received** reply (unobfuscated) len=0x0008:
**000: 14 05 04 00 6a 39 57 64   ....j9Wd**

**Comment by Carpintonto** [comment]
Yes, powered up normally, NOT in programming mode, with radio ON before plugging in.

**Comment by egzumer** [comment]
This is a communication issue. The radio echoes back what it receives, looks like a short between TX and RX lines. This not a driver or chirp problem.

**Comment by Carpintonto** [comment]
I wonder ... serial ports are enumerated starting at zero on Linux and at 1 on Windows.
Could the "short" be in the code?  I haven't read the entire driver.

I encountered this impasse configuring dial-up to work for both dual booting Windows and Linux.
It confounded me memorably.

**Comment by egzumer** [comment]
This has nothing to do with the driver or chirp. You can see in the log what is being sent to UART and what is being received. Serial port mirrors whatever it receives.

**Comment by Carpintonto** [comment]
I can avail a stock UV-K6.  I'll see if I can copy that with the original driver.
I can share results early next week.

**Comment by Carpintonto** [comment]
Sorry to have suggested the possibility of a coding error.
I hope you'll accept my apology.

The truth is, the cable has to be plugged in ALL the way!
When the microphone plug is fully seated, it works like a charm.

https://ham.stackexchange.com/a/22056
