### ISSUE TITLE
Programable Key ( key action) strange thing happen when upload to the radio...

### ISSUE THREAD

**Issue by joc2** [egzumer/uvk5-chirp-driver#33]
Strange Thing Happend.

 egzumer version 22 in the radio, 

i have one version of chirp,, the problem is their,
then install the last one, but same result:

![image](https://github.com/egzumer/uvk5-chirp-driver/assets/56229329/62e80bc4-c40b-4b3f-bbeb-839a728c16f7)

When you program any one of the programable key (F1 short,F1 Long,F2 short,F2 Long, M) to a value near the end of the list choice ( lock keypad ,switch ... ) directely in the radio via the M key ...

you read with chirp, it display the right thing in chirp. no problem their

The problem , if you change the key setting to a other choice selection in chirp, but uses the option in the bottom of the list, then upload it to the radio. The radio will not gone a show and do the option you program.......

example 1: program (switch demodulation) in chirp, send to the radio, then in the radio it show (switch vfo),
example 2: program (lock keypad ) in chirp, send to the radio, then in the radio it show (fm radio)
etc...
![image](https://github.com/egzumer/uvk5-chirp-driver/assets/56229329/b33cd8e6-8866-4abe-9cb1-aee74a9315f5)

but if you program the key setting with the top first few option . then every thing working fine. when uploading to the radio.

![image](https://github.com/egzumer/uvk5-chirp-driver/assets/56229329/28f25d82-be90-49f6-bdac-5925f5f00871)

it look like, that chirp have dificulty to handle a large option selection for a key.
 .

![image](https://github.com/egzumer/uvk5-chirp-driver/assets/56229329/4ed6c019-d82f-4be5-a4d4-232e5e35a10d)

I check the value send in the debug log of chirp when upload data to the radio. 
the value send is not good, if it's in the last value of the list, 

but if it's on the first value of the list, then the value are good..

maybe chirp have a max len list menu option and with this progammable key, it's over flow the buffer in chirp
so if it take a low value it not over flow.
it's done that on any of the key  programable you select.

it might match when egzumer integrate in chirp, not done test on older version chirp....

**Comment by joc2** [comment]
i just found that if i comment  the line that remove item not this firmware option, that correct the problem.  
#            if not has_alarm:
#                lst.remove("ALARM")

so mean something with pointer of the element number

**Comment by egzumer** [comment]
there is a bug, already fixed, not published yet
