### ISSUE TITLE
spectrum analyzer assignable to Side button

### ISSUE THREAD

**Issue by schinfo** [egzumer/uvk5-chirp-driver#36]
Unfortunately the function is still missing ;-)

**Comment by egzumer** [comment]
Did you build firmware from the latest commit?

**Comment by egzumer** [comment]
You have to be more specific then, because I have no idea what is missing.

**Comment by egzumer** [comment]
> I need the 1750Hz tone

Use PTT + side button 2. You don't need extra option for that.

**Comment by egzumer** [comment]
You probably used a driver py file from this repo, it was not updated. The primary repository where I maintain the driver now is the chirp itself, each change has to be pushed twice, to my repository and to chirp and it becomes too complicated, I will probably move to chirp repository only. 

The last change with spectrum function should be in the last official [release of chirp](https://trac.chirp.danplanet.com/chirp_next/next-20240224/)

I've updated this repository too just now.

**Comment by schinfo** [comment]
Works
