### ISSUE TITLE
Frequencies "out of supported range"

### ISSUE THREAD

**Issue by goopaga** [egzumer/uvk5-chirp-driver#8]
Hi, thanks for your great efforts with the FW and the CHIRP module as well.

In CHIRP i get "out of supported range" when typing a frequency equal or above 76.000 Mhz. I believe it is due to the Broadcast FM freq range that is stretched down to 76 Mhz and does not allow to use those frequencies.

At least in Europe the BFM is limited to the standard range 88-108 Mhz and the frequencies between 77 and 79 Mhz are used for safety services. 

Would it be possible to check on your side ?
Ideally would be useful a new setting to select the appropriate BFM range for the country so that outside of that range the frequencies can be used and programmed.

Best Regards

**Comment by goopaga** [comment]
Probably I've found out myself (very limited capabilities and understanding of coding) where to change the limits in your .py.

Anyway, still interesting to create a setting to choose the BFM limits depending on the coutry.


`
# fm radio supported frequencies
**FMMIN = 88.0**
FMMAX = 108.0

# bands supported by the UV-K5
BANDS_STANDARD = {
        0: [ 50.0, **88.0**],
        1: [108.0, 135.9999],
        2: [136.0, 199.9990],
        3: [200.0, 299.9999],
        4: [350.0, 399.9999],
        5: [400.0, 469.9999],
        6: [470.0, 600.0]
        }
`

**Comment by egzumer** [comment]
No issue whatsoever

![Screen Shot 12-23-23 at 06 09 PM](https://github.com/egzumer/uvk5-chirp-driver/assets/14902414/ec37ce95-65c4-4cc6-b01f-a96388c2a646)

**Comment by goopaga** [comment]
Mhh, weird. Tryied to replicate the issue but right now it works.
I could have messed up with previous saver config files.
SOrry for the issue and thanks for the head up.
