### ISSUE TITLE
Copy paste problem

### ISSUE THREAD

**Issue by f4axk** [egzumer/uvk5-chirp-driver#9]
Copy paste problem

![egzumer](https://github.com/egzumer/uvk5-chirp-driver/assets/68162981/e02716dd-bf59-4385-a1cc-bb9d4c310dbf)

**Comment by ErikS-web** [comment]
Could you zip your channellist and include in reply.

And explain what steps you are doing.

**Comment by f4axk** [comment]
test today

![egzumer](https://github.com/egzumer/uvk5-chirp-driver/assets/68162981/15393325-1c4a-4f48-8081-cf861923007a)

No problem copying/pasting csv to csv
problem to an img file.
The procedure I have always used.
chirp database fr marine VHF channels.csv
I copy 4 channels and paste in the uvk5 (egzumer).img file
and the error occurs.

I had problems before the latest version.

attached files  https://transfert.free.fr/7vaZF1z
